ESVER="elasticsearch-1.7.1"
ESDL="https://download.elastic.co/elasticsearch/elasticsearch/${ESVER}.tar.gz"
ESPATH="/root/elk/atlantis-elasticsearch"
CONFDIR="${ESPATH}/config-files"
ESDIR="${ESPATH}/${ESVER}"
ESCONF="${ESDIR}/config"
ATLANTISLOGDIR="/var/log/atlantis"
ESLOGDIR="${ATLANTISLOGDIR}/elasticsearch"

wget "$ESDL"
tar -xzf "${ESVER}.tar.gz"
rm *.gz
rm "${ESCONF}/logging.yml"
rm "${ESCONF}/elasticsearch.yml"
cp "${CONFDIR}/logging.yml" "${ESCONF}/"
mkdir "${ATLANTISLOGDIR}"
mkdir "${ESLOGDIR}" 
